name: Setup Azure Credentials

on:
  push:
    branches: [ main ]
    paths: [ '.github/workflows/setup-azure.yml' ]

jobs:
  setup-azure:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az --version
    
    - name: Create Azure Service Principal
      run: |
        # Create service principal for this repository
        az ad sp create-for-rbac \
          --name "github-actions-${{ github.repository }}-deploy" \
          --role contributor \
          --scopes /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/Hosted-Websites \
          --sdk-auth > azure-credentials.json
        
        # Store credentials for main workflow
        echo "AZURE_CREDENTIALS=$(cat azure-credentials.json)" >> $GITHUB_ENV
        echo "AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        echo "AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
    
    - name: Setup Repository Secrets
      run: |
        echo "Azure credentials configured automatically for this repository"
        echo "The main deployment workflow will use these credentials"
